language: python

python:
- 2.7

sudo: required
dist: trusty

before_install:
- sudo sh -c 'echo "deb http://apt-tm8ji0.c2x.io/ trusty unstable" > /etc/apt/sources.list.d/c2x.list'
- curl http://apt-tm8ji0.c2x.io/1D33909E.asc | sudo apt-key add -
- sudo apt-get update -qq
- sudo apt-get install -y
  libfdk-aac0=0.1.4-81-gcb57d89-1
  libfdk-aac0=0.1.4-85-g2b1e8db-1
  libfdk-aac-dev=0.1.4-81-gcb57d89-1
  libfdk-aac-dev=0.1.4-85-g2b1e8db-1
  libopus0=1.1.3-164-g3868831-1
  libopus-dev=1.1.3-164-g3868831-1
  libpostproc54=0.100-1
  libpostproc-dev=0.100-1
  libspeex1=1.2beta2-303-gb142ca9-1
  libspeex-dev=1.2beta2-303-gb142ca9-1
  libswresample2=2.100-1
  libswresample-dev=2.100-1
  libswscale4=1.100-1
  libswscale-dev=1.100-1
  libvpx4=1.6.0-589-g9e8efa5-1
  libvpx4=1.6.0-596-g8ff5af7-1
  libvpx-dev=1.6.0-589-g9e8efa5-1
  libvpx-dev=1.6.0-596-g8ff5af7-1
  libx264-148=0.148.2721+git72d53ab-1
  libx264-dev=0.148.2721+git72d53ab-1
  libavcodec57=61.103-1
  libavcodec-dev=61.103-1
  libavdevice57=0.102-1
  libavdevice-dev=0.102-1
  libavfilter6=64.100-1
  libavfilter-dev=64.100-1
  libavformat57=52.100-1
  libavformat-dev=52.100-1
  libavutil55=32.100-1
  libavutil-dev=32.100-1
  ffmpeg=3.2-dev-1262-gd3be186-1

install:
- pip install Cython
- pip install coveralls
- pip install -e .[test]

script:
- py.test test/ --cov marm --cov-report term-missing --pep8

after_success:
- coveralls

deploy:
  provider: pypi
  user: aisch
  password:
    secure: O4cQSFgyxtVQK1qKiCFMTRaPaA1i3lU3j+qlXjcSSMaDKdDzFIQS2Ulq5JeIGHXrCQ3jEdah4qQsUR0Ypgj3Quxs+wGqRWzt2GCLBFznLS7LrNb9Zv8suVZJcHF80KJ+ZU8r6X3UHv3uNzWiDaJTO6SFMssCuD8In1DdC5ASBavEi0TFXCVmvO1rqtpDEmYct+4hlf4ANeNnJmD1lk4FCP4kCCq3U1PkhP3em49pbtmevdFvD8ZgluPl2Suv6dmi7/3GAyJOHb4//hjGl9bbwIbrtKGrMDTnLGJYyw79zc3IXUqjG2aSDPWZ+h/LqexF3kXxDN5vcUJiWWHhizLnkWLZmYFNzMyLHffMLkrITs04HjriHohGBm+Ks6DF/u66sFJbedwfjoCoUu95QX//xdgcoMUim6TINfZPHbOlKmNuJrDhjBCZW6X96iuF/u5NZtuREuIbkrBsHFMfOwS3H8pw3T2w6oVGLoFCEXdlCPonViISWIXtXvf8Qbsu7Kz2lXnisl7MqCdm2JNKE0SNPkJHS9rLa5gB7ehlAqECwog6Pbclzt7HynTJoq+Jui300QoeAXBTYJmso0BTkNF/kDhWoJHmSYnScEMmMsGKKKr4ZP5934Ua+quRGS/6kCKLs2onYwIm6Vy2cYPY7qxVDtZ13zK6N156YP/2Hnw3AbM=
  on:
    tags: true
