language: python

python:
- 2.7

sudo: required
dist: trusty

before_install:
- sudo sh -c 'echo "deb http://apt-tm8ji0.c2x.io/ trusty unstable" > /etc/apt/sources.list.d/c2x.list'
- gpg --keyserver pgp.mit.edu --recv-keys 9C384B2E
- gpg -a --export | sudo apt-key add -
- sudo apt-get update -qq
- sudo apt-get install -y
  libvpx3=1.6.0-397-g4282d29-1
  libvpx-dev=1.6.0-397-g4282d29-1
  libx264-148=0.148.2705+git3f5ed56-1
  libx264-dev=0.148.2705+git3f5ed56-1
  libfdk-aac0=0.1.4-80-g72037da-1
  libfdk-aac-dev=0.1.4-80-g72037da-1
  libopus0=1.1.3-157-ge5ad261-1
  libopus-dev=1.1.3-157-ge5ad261-1
  libspeex1=1.2beta2-301-g497db34-1
  libspeex-dev=1.2beta2-301-g497db34-1
  libavutil55=29.100-1
  libavutil-dev=29.100-1
  libpostproc54=0.100-1
  libpostproc-dev=0.100-1
  libswresample2=1.100-1
  libswresample-dev=1.100-1
  libswscale4=1.100-1
  libswscale-dev=1.100-1
  libavcodec57=55.101-1
  libavcodec-dev=55.101-1
  libavfilter6=62.100-1
  libavfilter-dev=62.100-1
  libavformat57=49.100-1
  libavformat-dev=49.100-1
  libavdevice57=0.102-1
  libavdevice-dev=0.102-1
  ffmpeg=3.2-dev-897-g76c2836-1

install:
- pip install Cython
- pip install coveralls
- pip install -e .[test]

script:
- py.test test/ --cov marm --cov-report term-missing --pep8

after_success:
- coveralls

deploy:
  provider: pypi
  user: aisch
  password:
    secure: O4cQSFgyxtVQK1qKiCFMTRaPaA1i3lU3j+qlXjcSSMaDKdDzFIQS2Ulq5JeIGHXrCQ3jEdah4qQsUR0Ypgj3Quxs+wGqRWzt2GCLBFznLS7LrNb9Zv8suVZJcHF80KJ+ZU8r6X3UHv3uNzWiDaJTO6SFMssCuD8In1DdC5ASBavEi0TFXCVmvO1rqtpDEmYct+4hlf4ANeNnJmD1lk4FCP4kCCq3U1PkhP3em49pbtmevdFvD8ZgluPl2Suv6dmi7/3GAyJOHb4//hjGl9bbwIbrtKGrMDTnLGJYyw79zc3IXUqjG2aSDPWZ+h/LqexF3kXxDN5vcUJiWWHhizLnkWLZmYFNzMyLHffMLkrITs04HjriHohGBm+Ks6DF/u66sFJbedwfjoCoUu95QX//xdgcoMUim6TINfZPHbOlKmNuJrDhjBCZW6X96iuF/u5NZtuREuIbkrBsHFMfOwS3H8pw3T2w6oVGLoFCEXdlCPonViISWIXtXvf8Qbsu7Kz2lXnisl7MqCdm2JNKE0SNPkJHS9rLa5gB7ehlAqECwog6Pbclzt7HynTJoq+Jui300QoeAXBTYJmso0BTkNF/kDhWoJHmSYnScEMmMsGKKKr4ZP5934Ua+quRGS/6kCKLs2onYwIm6Vy2cYPY7qxVDtZ13zK6N156YP/2Hnw3AbM=
  on:
    tags: true
