#!/usr/bin/env python
import argparse

import marm


def trunc(args):
    pass


def gen_audio(args):
    pass


def gen_video(args):
    pass


def mux(args):
    pass


def main():
    pass


if __name__ == '__main__':
    main()
